# Generated by Django 4.0.4 on 2022-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Department', models.IntegerField()),
                ('MobileNo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='stud_data',
        ),
    ]
